version: "3.9"

services:
    expressdelivery:
      depends_on:
        - dataBaseExpressDelivery
      build: ./expressdelivery
      ports: 
        - "9010:9010"
      links:
        - dataBaseExpressDelivery
      restart: always
      environment:
        spring.datasource.url"  : jdbc:mysql://localhost:3306/expressdelivery

    drugdrop: 
      depends_on:
        - dataBaseDrugDrop
      build: ./drugdrop
      ports: 
        - "9014:9014"
      restart: always
      environment:
        spring.datasource.url  : jdbc:mysql://localhost:3306/drugdrop
        spring.datasource.username: drugdrop
        spring.datasource.password: drugdrop
        spring.datasource.driver-class-name: com.mysql.jdbc.Driver

    dataBaseExpressDelivery:
        image: mysql:8.0.29
        ports: 
            - 3308:3306
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: expressdelivery
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: expressdelivery
        volumes:
             - ./volumes/mysql/db:/var/lib/mysql
             - ./volumes/mysql/scripts:/docker-entrypoint-initdb.d

        restart: always
    
    dataBaseDrugDrop:
        image: mysql:8.0.29
        ports: 
            - 3309:3306
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: drugdrop
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: drugdrop
        volumes:
             - ./volumes/mysql/db:/var/lib/mysql
             - ./volumes/mysql/scripts:/docker-entrypoint-initdb.d
        networks:
            - default
        restart: always