version: "3.8"

services:
    expressdelivery:
      depends_on:
        - dataBaseExpressDelivery
      build: ./expressdelivery
      ports: 
        - "9010:9010"
      volumes:
        - ../expressdelivery/var/www/html/
        - ../expressdelivery/src/main/java/com/uatqs/expressdelivery/betIES/repository/*
      links:
        - dataBaseExpressDelivery
      networks:
        - default
      restart: on-failure
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://localhost:3306/expressdelivery",
          "spring.datasource.username" : "expressdelivery",
          "spring.datasource.password" : "expressdelivery",
          "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create",
          "server.port": 9010
         }'

    drugdrop: 
      depends_on:
        - dataBaseDrugDrop
      build: ./drugdrop
      ports: 
        - "9011:9011"
      volumes:
        - ../drugdrop/var/www/html/
      links:
        - dataBaseDrugDrop
      networks:
        - default
      restart: on-failure
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://localhost:3306/drugdrop",
          "spring.datasource.username" : "drugdrop",
          "spring.datasource.password" : "drugdrop",
          "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create",
          "server.port": 9011
         }'

    dataBaseExpressDelivery:
        image: mysql:8.0
        ports: 
            - 3030:3030
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: expressdelivery
            MYSQL_USER: expressdelivery
            MYSQL_ROOT_PASSWORD: expressdelivery
            MYSQL_PASSWORD: expressdelivery
        volumes:
             - ./volumes/mysql/db:/var/lib/mysql
             - ./volumes/mysql/scripts:/docker-entrypoint-initdb.d
        networks:
            - default
        restart: always
    
    dataBaseDrugDrop:
        image: mysql:8.0
        ports: 
            - 3031:3031
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: drugdrop
            MYSQL_USER: drugdrop
            MYSQL_ROOT_PASSWORD: drugdrop
            MYSQL_PASSWORD: drugdrop
        volumes:
             - ./volumes/mysql/db:/var/lib/mysql
             - ./volumes/mysql/scripts:/docker-entrypoint-initdb.d
        networks:
            - default
        restart: always