version: "3.9"

services:
    expressdelivery:
      depends_on:
        dbExpressDelivery:
          condition: service_healthy
      build: ./expressdelivery
      ports: 
        - "9010:9010"
      links:
        - dbExpressDelivery
      restart: on-failure
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://dbExpressDelivery:3306/expressdelivery
        SPRING_DATASOURCE_USERNAME: expressdelivery
        SPRING_DATASOURCE_PASSWORD: expressdelivery

    drugdrop: 
      depends_on:
        dbDrugDrop:
          condition: service_healthy
      build: ./drugdrop
      ports: 
        - "9014:9014"
      restart: on-failure
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://dbDrugDrop:3306/drugdrop
        SPRING_DATASOURCE_USERNAME: drugdrop
        SPRING_DATASOURCE_PASSWORD: drugdrop

    dbExpressDelivery:
        image: mysql:5.7
        ports: 
            - 33062:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: expressdelivery
            MYSQL_USER: expressdelivery
            MYSQL_PASSWORD: expressdelivery
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dbExpressDelivery:/var/lib/mysql
        restart: on-failure
        healthcheck:
         test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'expressdelivery', '-pexpressdelivery' ]
         timeout: 5s
         retries: 10
    dbDrugDrop:
        image: mysql:5.7
        ports: 
            - 33061:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: drugdrop
            MYSQL_USER: drugdrop
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: drugdrop
        volumes:
            - ./dbDrugDrop:/var/lib/mysql
        networks:
            - default
        restart: on-failure
        healthcheck:
          test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'drugdrop', '-pdrugdrop' ]
          timeout: 5s
          retries: 10